# ==============================================================================
# Aether OS - Kitty Terminal Configuration
# Paleta de cores escura e minimalista (Ice Blue / Deep Cyan / Charcoal)
# ==============================================================================

# Tipografia
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.5

# Espaçamento e layout de janela
window_padding_width 12
confirm_os_window_close 0
remember_window_size  yes
initial_window_width  950
initial_window_height 600

# Paleta de Cores Aether Dark
background #101419
foreground #e2e8f0
selection_background #0087af
selection_foreground #ffffff
cursor #00afff
cursor_text_color #101419

# Cores Normais (0-7)
color0 #1a202c
color1 #ff5555
color2 #50fa7b
color3 #f1fa8c
color4 #0087af
color5 #bd93f9
color6 #00afff
color7 #bfbfbf

# Cores Brilhantes (8-15)
color8  #4a5568
color9  #ff6e6e
color10 #69ff94
color11 #ffffa5
color12 #5fafff
color13 #d6acff
color14 #5fffff
color15 #ffffff
